import '~/app/globals.css';

import type { Metadata, Viewport } from 'next';
import { Fraunces, Geist } from 'next/font/google';

import { Nav } from '~/components/nav';
import { AnalyticsProvider } from '~/components/posthog-provider';
import { Providers } from '~/components/providers';
import { RouteChrome } from '~/components/route-chrome';
import { SaaSMakerFeedback } from '~/components/saasmaker-feedback';
import { SiteFooter } from '~/components/site-footer';
import { VitalsReporter } from '~/components/VitalsReporter';

const geist = Geist({ subsets: ['latin'], display: 'swap', variable: '--font-sans' });
const fraunces = Fraunces({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-serif',
  axes: ['opsz'],
});

export const metadata: Metadata = {
  title: {
    default: 'Significant Hobbies — Personal Apps',
    template: '%s | Significant Hobbies',
  },
  description: 'A simple directory for Live, Journal, Calorie, Setline, Kith, and Anchor.',
  keywords: ['personal apps', 'local-first apps', 'bucket list', 'journal', 'focus'],
  authors: [{ name: 'Significant Hobbies' }],
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-image-preview': 'large',
      'max-snippet': -1,
      'max-video-preview': -1,
    },
  },
  manifest: '/manifest.json',
  icons: [
    { rel: 'icon', url: '/favicon.svg', type: 'image/svg+xml' },
    { rel: 'icon', url: '/icon.svg', type: 'image/svg+xml' },
    { rel: 'icon', url: '/favicon.ico', sizes: 'any' },
    { rel: 'apple-touch-icon', url: '/apple-touch-icon.png' },
  ],
  appleWebApp: {
    capable: true,
    statusBarStyle: 'default',
    title: 'Significant Hobbies',
  },
  formatDetection: { telephone: false },
  openGraph: {
    type: 'website',
    siteName: 'Significant Hobbies',
    url: 'https://significanthobbies.com',
    title: 'Significant Hobbies — Personal Apps',
    description:
      'A simple directory for Live, Journal, Calorie, Setline, Kith, and Anchor.',
    images: [
      {
        url: 'https://significanthobbies.com/opengraph-image',
        width: 1200,
        height: 630,
        alt: 'Significant Hobbies personal apps',
      },
    ],
  },
  metadataBase: new URL('https://significanthobbies.com'),
  twitter: {
    card: 'summary_large_image',
    title: 'Significant Hobbies — Personal Apps',
    description: 'Six focused personal apps in one simple directory.',
    images: ['https://significanthobbies.com/opengraph-image'],
  },
};

export const viewport: Viewport = {
  themeColor: '#0c2b29',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${geist.variable} ${fraunces.variable}`}>
      <head>
        {/* fleet-jsonld:start (generated by apply-agent-surfaces; edit registry, not this) */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: `{"@context":"https://schema.org","@graph":[{"@type":"Person","@id":"https://sarthakagrawal.dev/#person","name":"Sarthak Agrawal","jobTitle":"AI Infrastructure & Product Engineer","url":"https://sarthakagrawal.dev","image":"https://avatars.githubusercontent.com/u/43884471?v=4","sameAs":["https://sarthakagrawal.dev","https://www.linkedin.com/in/sarthakagrawal927","https://github.com/sarthakagrawal927","https://x.com/sarthakcodes","https://huggingface.co/sarthakagrawal927"],"knowsAbout":["AI infrastructure","Local-first software","Post-training language models","AI code review","Cloudflare Workers","TypeScript","Rust"],"affiliation":{"@type":"Organization","@id":"https://sassmaker.com/#app","name":"SaaS Maker","url":"https://sassmaker.com"}},{"@type":"Organization","@id":"https://significanthobbies.com/#org","name":"Significant Hobbies","url":"https://significanthobbies.com","contactPoint":{"@type":"ContactPoint","contactType":"customer support","email":"sarthakagrawal@agentmail.to","url":"https://significanthobbies.com"},"address":{"@type":"PostalAddress","addressCountry":"US"}},{"@type":"WebSite","@id":"https://significanthobbies.com/#app","name":"Significant Hobbies","alternateName":["SignificantHobbies","significanthobbies.com"],"url":"https://significanthobbies.com","description":"The shared Hub for Live, Journal, Calorie, Setline, Kith, and Anchor, backed by one privacy-aware control plane.","publisher":{"@id":"https://sarthakagrawal.dev/#person"},"sameAs":["https://github.com/Significant-Hobbies/significanthobbies"]}]}`,
          }}
        />
        {/* fleet-jsonld:end */}
        {/* Microsoft Clarity — session replay + heatmaps (additive; PostHog stays) */}
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(c,l,a,r,i,t,y){c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/y6btx9iks3";y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);})(window,document,"clarity","script","y6btx9iks3");window.clarity("set","project_id","significanthobbies");`,
          }}
        />
      </head>
      <body
        className={`${geist.variable} ${fraunces.variable} min-h-screen bg-background text-foreground font-sans antialiased`}
      >
        <AnalyticsProvider>
          <Providers>
            <a
              href="#main"
              className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-[100] focus:rounded-md focus:bg-primary focus:px-4 focus:py-2 focus:text-sm focus:font-semibold focus:text-primary-foreground"
            >
              Skip to content
            </a>
            <RouteChrome
              navigation={<Nav />}
              footer={<SiteFooter />}
              feedback={<SaaSMakerFeedback />}
            >
              {children}
            </RouteChrome>
            <VitalsReporter />
          </Providers>
        </AnalyticsProvider>
        <script
          src="https://sassmaker.com/project-strip.js"
          data-project="significanthobbies"
          defer
        />
        <script
          src="https://sassmaker.com/ai-chat-footer.js"
          data-name="Significant Hobbies"
          defer
        />
      </body>
    </html>
  );
}
